stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Running tests"
    - python3 --version

deploy:
  stage: deploy
  script:
    - echo "Deploying to EC2"
    - ssh ubuntu@<EC2-PUBLIC-IP> "cd app || git clone https://gitlab.com/your-username/devops-exp2.git app && cd app && git pull && python3 app.py"